Trazendo o histórico dos cálculos que foram efetuados sem paginar
alisson-fs/poc-bridge pull request #10
Opened 2022-11-17 19:46 UTC by alisson-fs

2023-05-05 19:37 UTC, zDudaHang requested changes
Boa !
Pedindo request por causa de algumas dúvidas e também porque faltaram os testes para os resolvers ;)

2023-05-05 19:37 UTC, zDudaHang commented on backend/pom.xml
> +			<version>14.0.0</version>
Aqui não daria para usar a versão mais atual ?

2023-05-05 19:37 UTC, zDudaHang commented on backend/src/main/kotlin/br/alisson/poc/ImcQueryResolver.kt
> +    fun historicoBetween(dataInicio: String, dataFim: String, tamanho: Int): Page<Imc> {
Uma dúvida: o kotlin não tem polimorfismo para permitir a mesma função com parâmetros diferentes ou dá problema por causa do graphql ?

2023-05-05 19:37 UTC, zDudaHang commented on backend/src/main/kotlin/br/alisson/poc/ImcResolver.kt
> +        return ImcUtils.formatUsToBr(imc.altura)
Uma sugestão: talvez criar métodos de extensão para essa conversão, o que cê acha ?

2023-05-05 19:37 UTC, zDudaHang commented on backend/src/main/kotlin/br/alisson/poc/ImcResolver.kt
> +         return formatDate(imc.data)
Aqui vale a mesma sugestão

2023-05-05 19:37 UTC, zDudaHang commented on backend/src/main/kotlin/br/alisson/poc/util/ImcUtils.kt
> +            val pattern = "dd/MM/yyyy HH:mm"
Como o pattern não vai mudar, me parece fazer mais sentido isso ser uma constante ;)

2023-05-05 19:37 UTC, zDudaHang commented on backend/src/main/resources/application.yaml
> +#      allowed-headers: "*"
Não vale remover isso ?

2023-05-05 19:37 UTC, zDudaHang commented on backend/src/main/kotlin/br/alisson/poc/model/Imc.java
> +		return data;
Eu não lembro se conversamos sobre isso, mas com o lombok dá ruim ?

2023-05-05 19:37 UTC, zDudaHang commented on backend/src/main/resources/schema.graphqls
> +    historicoBetween(dataInicio: String, dataFim: String, tamanho: Int): [Imc!]!
Só para confirmar, não tem como essa lista vir `null`, certo ?

2023-05-05 19:37 UTC, zDudaHang commented on backend/src/main/resources/schema.graphqls
> +    historicoBetween(dataInicio: String, dataFim: String, tamanho: Int): [Imc!]!
Como são vários atributos, será que não vale usar uma [input](https://graphql.org/graphql-js/mutations-and-input-types/) ?

2023-05-05 19:37 UTC, zDudaHang commented on frontend/graphql.config.yaml
> +      - 'typescript-react-apollo'
Se for utilizar as inputs, talvez vale dar uma olhadinha na parte de geração com kotlin dessa ferramenta, o que cê acha ?

2023-05-05 19:37 UTC, zDudaHang commented on frontend/src/App.tsx
> +  const theme = useTheme();
Ué
Tem algo de errado no formatter, não ?

2023-05-05 19:37 UTC, zDudaHang commented on frontend/src/App.tsx
> +        }}
Para facilitar a manutenção futura e não misturar estilos com os componentes, acredito que vale separar os estilos em uma função separada fora do componente, como é feito no PEC

2023-05-05 19:37 UTC, zDudaHang commented on frontend/src/components/ImcQuery.gql
> +    data
Como está repetindo os campos que estão sendo buscados e as duas queries retornam o mesmo modelo, vale utilizar um fragment :relaxed:

2023-05-05 19:37 UTC, zDudaHang commented on frontend/src/components/ImcQuery.gql
Acho importante separar em dois arquivos também !

2023-05-05 19:37 UTC, zDudaHang commented on frontend/src/utils/__generated__/graphql.ts
Acredito que vale adicionar isso no .gitignore como cê comentou hoje

2023-05-05 19:37 UTC, zDudaHang commented on frontend/src/index.tsx
> -  <React.StrictMode>
Uma dúvida: Qual seria o impacto disso na aplicação ?

2023-05-05 19:37 UTC, zDudaHang commented on frontend/src/components/Historico/model.ts
Para evitar essa criação de constantes sempre que é criada uma modelagem junto, será que não vale ver uma forma para criar isso sozinho pegando as keys do objeto ? Seria um `metaPath` bem simplificado do PEC

2023-05-05 19:37 UTC, zDudaHang commented on frontend/src/components/Historico/validate.ts
> +  errors = validateGreaterThan(errors, values, TAMANHO, -1);
O tamanho não deveria ser maior que 0 ?

2023-05-05 19:37 UTC, zDudaHang commented on frontend/src/components/Periodo.tsx
> +import { css } from "@emotion/core";
Aqui não precisaria usar o pragma do `jsx` ?

2023-05-05 19:37 UTC, zDudaHang commented on frontend/src/components/Fomulario/Formulario.tsx
> +  const [resultado, setResultado] = useState<Number>(0);
Acredito que seja melhor manter em um tipo primitivo, não ?

2023-05-10 12:47 UTC, alisson-fs commented on backend/src/main/kotlin/br/alisson/poc/ImcQueryResolver.kt
> +    fun historicoBetween(dataInicio: String, dataFim: String, tamanho: Int): Page<Imc> {
O kotlin tem polimofismo, fiz dessa forma porque tive problemas com o graphql. Vou ver se alterando a logica dos atributos para um input eu consigo utilizar uma query só.

2023-06-21 13:53 UTC, alisson-fs commented on backend/src/main/kotlin/br/alisson/poc/model/Imc.java
> +		return data;
Esses gets foram feitos na mão porque dava problema ao tentar utilizá-los no kotlin quando eram gerados por uma annotation do java.

2023-06-29 17:35 UTC, alisson-fs commented on backend/src/main/resources/schema.graphqls
> +    historicoBetween(dataInicio: String, dataFim: String, tamanho: Int): [Imc!]!
Ela pode vir undefined.

2023-07-05 18:49 UTC, alisson-fs commented on frontend/src/App.tsx
> +  const theme = useTheme();
Acho que não, por que?

2023-07-05 20:01 UTC, alisson-fs commented on frontend/src/index.tsx
> -  <React.StrictMode>
Eu não lembro o porque de ter tirado isso, vou colocar de volta, caso quebre algo eu aviso.

2023-07-05 20:03 UTC, alisson-fs commented on frontend/src/components/Historico/validate.ts
> +  errors = validateGreaterThan(errors, values, TAMANHO, -1);
Eu coloquei assim porque se o usuário colocar 0 o histórico fica sem resultados e achei que não deveria ter a obrigação de ter um dado no historico.

2023-07-21 16:04 UTC, alisson-fs commented on backend/src/main/kotlin/br/alisson/poc/util/ImcUtils.kt
> +            val pattern = "dd/MM/yyyy HH:mm"
```val``` já não é suficiente?

2023-07-21 16:05 UTC, alisson-fs commented on frontend/src/components/Periodo.tsx
> +import { css } from "@emotion/core";
Como conversamos via slack, devido aos problemas encontrados isso será alterado no futuro.

2023-07-21 16:08 UTC, alisson-fs commented on backend/pom.xml
> +			<version>14.0.0</version>
Eu não consegui fazer essa alteração, tentei colocar para pegar a versão mais recente automaticamente também mas não deu certo.

2023-07-21 16:08 UTC, alisson-fs commented on backend/src/main/kotlin/br/alisson/poc/ImcResolver.kt
> +        return ImcUtils.formatUsToBr(imc.altura)
Como assim métodos de extensão?

2023-08-08 17:00 UTC, zDudaHang requested changes
Boa !

2023-08-08 17:00 UTC, zDudaHang commented on frontend/package.json
> +    "@emotion/styled": "^11.11.0",
Acho que vale remover essas dependências já que não deu certo com o emotion

2023-08-08 17:00 UTC, zDudaHang commented on frontend/src/components/Historico/Historico.tsx
> +      fetchPolicy: "network-only",
Aqui não poderia liberar para a cache trazer ?

2023-08-08 17:00 UTC, zDudaHang commented on frontend/src/components/Historico/Historico.tsx
> +          tamanho: values.tamanho,
Aqui não precisaria de um null safety também ? Ou não precisa no `values` ?

2023-08-08 17:00 UTC, zDudaHang commented on frontend/src/components/Historico/Historico.tsx
> +
Acredito que esses renders poderiam ficar fora do componente já que não dependem das props ou resultados de hooks

2023-08-08 17:00 UTC, zDudaHang commented on frontend/src/components/Historico/Historico.tsx
> +            <CampoTexto for={TAMANHO} name={TAMANHO} label="Tamanho: " inline />
Acho que como uma possível melhoria seria criar um componente só para valores numéricos (mas isso seria feito **em outro momento**)

2023-08-08 17:00 UTC, zDudaHang commented on frontend/src/components/Historico/Historico.tsx
> +                handleSubmit();
```suggestion
                handleSubmit()
```

2023-08-08 17:00 UTC, zDudaHang commented on frontend/src/components/Historico/Historico.tsx
> +            <Button
Eu vejo muito `type='submit'` quando é formulário, acho que é bom dar uma olhadinha se não vale colocar essa prop

2023-08-08 17:00 UTC, zDudaHang commented on frontend/src/components/Historico/Historico.tsx
> +        validate={validateTamanho}
Não existem validações para o período, certo ?

2023-08-08 17:00 UTC, zDudaHang commented on frontend/src/components/Historico/__test__/validate.test.ts
Foram comentados pela questão de usar o spy ou porque não está dando bom ?

2023-08-08 17:00 UTC, zDudaHang commented on frontend/src/components/ImcQuery.gql
Aqui não faltou mudar o nome do arquivo ?

2023-08-08 17:00 UTC, zDudaHang commented on frontend/src/components/Periodo.tsx
Será que não vale mudar o nome para CampoPeriodo ? Acho que deixaria mais claro que faz parte de um formulário

2023-08-08 17:00 UTC, zDudaHang commented on frontend/src/utils/__generated__/graphql.ts
Será que isso não poderia estar no `.gitignore` ?

2023-08-08 17:00 UTC, zDudaHang commented on backend/src/main/kotlin/br/alisson/poc/config/WebConfiguration.kt
Uma melhoria futura aqui seria pegar essas configurações de um `.properties`, mas isso seria feito **em outro momento**

2023-08-08 17:00 UTC, zDudaHang commented on backend/src/main/resources/schema.graphqls
> +    historico(input: HistoricoInput): [Imc!]!
A input não é obrigatória?

2023-08-08 17:00 UTC, zDudaHang commented on backend/src/main/kotlin/br/alisson/poc/ImcQueryResolver.kt
> +            repository.findByDataBetween(Instant.parse(input.dataInicio), Instant.parse(input.dataFim), pageable)
Como você está convertendo aqui, já não vale o servidor receber isso pronto do cliente ?

2023-10-06 17:03 UTC, alisson-fs commented on frontend/src/utils/__generated__/graphql.ts
Tinha colocado la mas n tinha atualizado o branch sem ele

2023-10-06 17:09 UTC, alisson-fs commented on frontend/src/components/Historico/__test__/validate.test.ts
Pelo que me lembro estava dando ruim por algum motivo, mas agora está funcionando.

2023-10-06 17:27 UTC, alisson-fs commented on frontend/src/components/Historico/Historico.tsx
> +          tamanho: values.tamanho,
O tamanho é obritatório.

2023-10-09 14:25 UTC, zDudaHang approved these changes

2023-10-09 14:25 UTC, zDudaHang commented on backend/src/main/kotlin/br/alisson/poc/HistoricoInput.kt
> +        val dataFim: Instant?,
Acredito que aqui daria para ser LocalDate, já que a sua aplicação parece estar mais preocupada com a data em si

2023-10-09 14:25 UTC, zDudaHang commented on backend/src/main/kotlin/br/alisson/poc/util/ImcUtils.kt
> +            val pattern = "dd/MM/yyyy HH:mm"
Nops, daria para deixar isso fora do método porque não é para mudar, entende ?

2023-10-09 14:25 UTC, zDudaHang commented on frontend/src/components/CampoPeriodo.tsx
> +    <>
Humm, aqui não deveria usar o `Fragment` do react ?

2023-10-09 14:25 UTC, zDudaHang commented on frontend/src/components/CampoPeriodo.tsx
> +import { css } from "@emotion/react";
O emotion será mantido ou vai usar o `styles` nas props ?

2023-10-09 14:25 UTC, zDudaHang commented on frontend/src/components/Historico/Historico.tsx
> +    console.log(values);
:eyes:

2023-10-09 14:25 UTC, zDudaHang commented on frontend/src/components/Historico/__test__/validate.test.ts
> +describe("validate", () => {
:heart:

2023-11-03 13:28 UTC, alisson-fs commented on frontend/src/components/CampoPeriodo.tsx
> +import { css } from "@emotion/react";
Nas props.

2023-11-03 13:34 UTC, alisson-fs commented on backend/src/main/kotlin/br/alisson/poc/HistoricoInput.kt
> +        val dataFim: Instant?,
A informação de hora está sendo colocada no histórico também, acho que seria interessante manter instant por isso.

2023-11-03 14:13 UTC, merged