Utilização da biblioteca Final-Form
alisson-fs/poc-bridge pull request #2
Opened 2022-06-10 19:33 UTC by alisson-fs

2022-06-24 19:11 UTC, zDudaHang requested changes

2022-06-24 19:11 UTC, zDudaHang commented on src/util.ts
> +  console.log(altura, peso)
Faltou tirar o `console.log` aqui

2022-06-24 19:11 UTC, zDudaHang commented on src/util.ts
> +  if (altura && peso) {
Como você adicionou a validação no formulário, acredito que essa verificação não seja mais necessária

2022-06-24 19:11 UTC, zDudaHang commented on src/components/Formulario.tsx
> +type ErrorObject<DataType> = { [key in keyof DataType]?: ErrorObject<DataType[key]> | string };
Será que isso não poderia ir para um `model.ts` ?

2022-06-24 19:11 UTC, zDudaHang commented on src/components/Formulario.tsx
> +            }
Será que essas verificações não poderiam virar métodos separados ? Por exemplo, poderia ter os seguintes métodos `validateRequired`, `validateOnlyNumbers`, `validateGreaterThan`
O que você acha ?

2022-06-27 20:39 UTC, alisson-fs commented on src/components/Formulario.tsx
> +            }
Concordo, mas fiz um pouco diferente do sugerido. A validação de campo obrigatório define se as outras validações ocorrerão, por conta disso tive que fazer um pouco diferente. Além disso eu fiz um metodo de validação de cada campo para cada um dos casos porque foi a forma que consegui pensar que funcionasse (`validateAlturaOnlyNumbers` e `validatePesoOnlyNumbers` por exemplo). Você acha que eu devo fazer essas validações de campos diferentes na mesma função?

2022-06-27 21:18 UTC, zDudaHang requested changes
Muito melhor, Alisson ! :rocket: 
Encontrei alguns pontos de melhoria no código

2022-06-27 21:18 UTC, zDudaHang commented on src/util.ts
>    return resultado;
Acredito que aqui poderia ser apenas `return peso / (altura / 100) ** 2`
O que você acha ?

2022-06-27 21:18 UTC, zDudaHang commented on src/model.ts
> +
Como esse `ErrorObject` trata apenas das validações e não tem relação com o `FrasesMotivacionaisContextModel`, acredito que seria mais interessante criar um `model.ts` separado apenas para as validações, tipo: `src/validation/model.ts`
O que você acha ?

2022-06-27 21:18 UTC, zDudaHang commented on src/components/Formulario.tsx
> +          errors = validate(errors, values);
Acredito que aqui já poderia ser um `return`, já que não será feito mais nada com o `errors`

2022-06-27 21:18 UTC, zDudaHang commented on src/validate.ts
> +const greaterThanZero = "Deve ser um valor maior do que 0.";
Como esses valores não vão mudar, acredito que poderiam estar com nome de constante, ex: `REQUIRED` / `ONLY_NUMBERS`

2022-06-27 21:18 UTC, zDudaHang commented on src/validate.ts
> +  return errors;
Alguns pontos que acho interessante ressaltar:
- Se você observar os métodos `validate...OnlyNumbers` e `validate...GreaterThanZero` eles seguem a mesma estrutura, a única coisa que muda é qual **atributo** (**_chave de um objeto/tipo_**) do `values` é verificado e para qual **atributo** do `errors` é atribuída a mensagem de erro --> Isso poderia virar algo mais **genérico** para você conseguir usar em qualquer campo de qualquer formulário e reduziria drasticamente a quantidade de funções necessárias para validar também 
- Acho que seria melhor criar uma função `validateRequired` porque o comportamento é muito parecido e assim você evitaria uma cópia de código em todos os validadores que necessitarem verificar isso, bastaria usar a função

Existem dois caminhos para você tratar a questão de depender da required para não validar as outras regras:
1. As próprias funções de validação podem fazer isso (se o valor for `null` ou `undefined`, basta não validar e seguir em frente)
2. Adicionar uma flag, tipo `isValid`, no seu `ErrorObject` para controlar se está válido ou não, aí bastaria dar um `if (errors.isValid) para chamar os outros validadores (que nem no back)

A opção 1 é mais fácil de implementar, enquanto a 2 teria vantagens na hora de testar (bastaria dar um assert true no `errors.isValid`)

2022-06-27 21:18 UTC, zDudaHang commented on src/validate.ts
> +  return errors;
Sobre o `validate...GreaterThanZero`, acredito que esse método poderia ser um pouco mais genérico para aceitar qualquer valor e adaptar a mensagem de erro conforme o parâmetro recebido
O que você acha ?

2022-06-27 21:18 UTC, zDudaHang commented on src/validate.ts
> +  return errors;
Sobre os pontos que comentei ali em cima, você vai precisar entender os genéricos no Typescript
Seguem algumas referências:
1. [Documentação sobre genéricos](https://www.typescriptlang.org/docs/handbook/2/generics.html)
2. [Playground para brincar com os genéricos](https://www.typescriptlang.org/pt/play?#code/PTAEBUEsAcHsGdQHMCmA7AlwJ0gYwaNClgLaQAuKJoArvAIZYQwH4mygBujkAh5ykiIqoWDXJYC5FvAB0AWABQIUAFkU5ekqUrw6TVioES9NJSYp4lUCgAeVaABsOjlANmgAarFwArwrAAJiigAGb0AF7EOmAkNBT0oPhCiWyg0nCIqJg4+MKgGISSnPwojqAAjjQhAgBWifSOSDTUuADPgZBIHABGVDFJsCROePSBHHSm4+kyyOjYeAQijc3UcGYcALSgJohC8LADaADHHPBdaJCho5XVM5lzOYuI8KeDw46j43LaymCe9HYiDYKAA54x3rRqHYHM5RGhgjY0JxYI4BIYgVDRD1ahoOIj9Fgxlo-jZqC1QIwiQBPDwAZTaXEBBDQBEgw1gWAMkJaiW4OFK5TQlmsuHoBwAXAMOBkOFUQqFYJBCOKGNM2BxGKt9LApYolKEaGhcNJYGgkSi0cQAKIkACCWBpAB4oHAAHwACkJxIlzDgAEpfa7YABtAC6oAA3kpQKBDOQaFhzSHvYF6GGANxKAC+vxUADlYJpfYU2BT0X6zsQ4yhQsRIOqhhxwB4AJLwA4FAa4GiOBNExwkfQhc5kRwQ1JNymIIgd2Di2gMajKkQU5ywaBhTkDaCMRKGaCGeD6CEAW4ReBQHnAoFZpEaQ7MIQPR5PldAHvA1KI-oANEjyFOAZJgxAgOFZId3icPEVSJHZ6EgTkknHQwIhJAZCw7RJDTQUE3hA3hQEgNA6ywXxjUgRJdzg49hkMeCnyYGUWB3VUxg4DVKSwbUNiI5pGkpZi4BrchOTQdiPzgLAMBIAZ0EtTgGw4VdqCpehqX9X58DQKxQCsHA0CQB0aVAABeC1UXRW1jPUj0ACIAAsyjhbJ61weA7P9LNFG03S0BaPosBs6kzIsq0sGsx1bIARgAJgAZi8vMwAABSCIxEHRK5RiYeUiLnMIjVwRDxPeZT4CIIlpnoDinLFLABmPAJgkxegJEgHp4iYCk1JCxF9OIpBEESXlCtwt55QGYIssSY9utUqK+pCWAcTxeAlF88hbxq4KABEUDpdrDPgX0BsM8NQvkyybXtRaPUjbMkv1UlvD8dJAR6GTmpCNwEiYRJiNI8jioaTpirNKZDlJISOBRN6h3gdg9U2riaX2w6DKG2LLuRa6Itu50zqQT07M87y5Nx8LIpMyqyGsPKqkaeUmFlPSUHqRd2P-KSvrsIRKFk0kxQORAzUROH-EPFBioYQhiDpyB-qIcTEApeAaB6bTaiNUTQERWUflJfNLGPYFxQICXvr1yAolyu4Yb1twfqsdBgnmgZWcsIhcFPa58AUZ7iPMcJcBCfbjzQBz6AEcpo0UWNggjqOsF9D1-TMt0uCVQJvNzZ6VGtKxsKNPCOEMUO+ixLWdfxZbVtExA8sydWVOL8aoZUajEkT9Bk+29IyhJHCTRKmsEXrNCsHzeg9HHF0WBsWxKARRBw976Oyk9VN6CDFhw3TuPY232RFQi+hcAcj1lVMzPIFkHvI8YNOnrzjazV0lbcQbgBhIY18fpg5kQyRkdknRgqd043yjNmUA2Z-wgIfsnCBGdoGwMzEoQw48cCT2nrPegHpP5rV-iQf+ycnoDHbJ2cIjhk6ESaogiEJxyrSArFLCOlA9QYNdhPRguDB4emAXAqMoD14pw-JAzOD00HkNJMGLI8xcgEDgC1d4YIJywWltWNgIwxTfFuJDLOb0BYDBIAAL77DAccmUeClCEB4O0VQVxWEIhSGEHxa5QjbqXR2SRz4OUGgMJu8sKAhDypbZeUdrakWHMCM02sNiIH1rMAkZgqokhUCEMUF9LAByUEHYgIcQgAAkEDkH2t-PxIRD56UaPyVOO9KRoA0iglEDZc6-GHqac0Yw8AlUYAAeXrrAO0sAKnZPnnAf8YynKL2XoERAJSrDlMqZ6T+u9Jm+Oyb6aZKBAygB2VGGMmynKyAYGiJ+n8nqxnjImc0WSnLtPzmAQu1hCgcARuwResI5R3HPuyeg3NORfTSBSaiAAjocEhlJLyJAHAsRYGldzCJEXwmw4TDz6VgQF0kSD-hYRlW4IQQKNNpKAShHcwDKJHNWI8lklKcwRBMEwRFGKFMeAsMUvx8lYDZYsspKAdkAHF0BuVgBM2A5SzSUBoOMSRRyzl1I-A04MkqnwytgBIrObSczJVAHabocFGaMtEKAPlyzsnCuFIogonNxj-kttNEInRbYDG7mUUJNABJvMrKq6V4wOlFS6ZSMGmLBlf1gK6diIydniqmZU2ZrsFmlPNU5S1orxVulWTidZsB-z3JQNsypeyDnVPzac2pFycRXJErc45KBHkDH6V89xlJirMsKH0ZcT4dLKWoOYTE-Ug70HsB4NKOLfwDH2BwQ8sBOD+FGseZoRJcKJBMIhLAHhC4MBeG8Sw+AaELkmqSegBq+Q+H8ALQYkdpbsh1LBbCkRiAeAAIqeuNafIos7qx2hSu2V1ohxBEhnCbec8A8WzGyBysC0TQ7kmoLiCgHBQiuFsKeGOPjaYUEVoEu4g9Va0TZnQIobRDyIUQAbNmfbqx5UBvWJgx4aBJA6F0adSFtGuFErk0kKU9zwSEM2pwBAkkPEg4o2JrQrGmxsCy4O59LB6hAHJWwgJoISjGNwY0KBAibFwJJywSmVOuAlOQb8e6cDQHIJsAA7hQBymxDDn3IAMBy5ByDQBOiAKzXnZAmdnLgcz5BxyGVkJyJAwBxjuWAFHBEPRYCwAANbAFcrkOQLmSCOCUEAA)
3. [Documentação sobre o operador keyof](https://www.typescriptlang.org/docs/handbook/2/keyof-types.html)
4. [Tutorial de como usar as keys de um Object para pegar os valores dos atributos](https://bobbyhadz.com/blog/typescript-object-get-key-by-value)

2022-07-05 00:54 UTC, zDudaHang requested changes
Top demais !
Acredito que faltam alguns detalhes ainda, mas tá ficando muito bom :relaxed:

2022-07-05 00:54 UTC, zDudaHang commented on src/validation/validate.ts
> +const GREATER_THAN_ZERO = "Deve ser um valor maior do que 0.";
Acredito que essas mensagens poderiam ir para o `model.ts` também

2022-07-05 00:54 UTC, zDudaHang commented on src/validation/validate.ts
> +    errors[name] = GREATER_THAN_ZERO;
Acredito que aqui a mensagem deveria se adequar de acordo com o `limit` passado

2022-07-05 00:54 UTC, zDudaHang commented on src/validation/validate.ts
> +}
Como essas funções não são genéricas, ou seja, que não poderiam ser usadas por qualquer formulário, acredito que seja mais adequado deixá-las junto com o formulário
Por exemplo: Criar uma pasta chamada `imc` ou `formulario-imc`, passar o `Formulario.tsx` para lá e criar um arquivo chamado `validator` para essas funções

2022-07-05 00:54 UTC, zDudaHang commented on src/validation/validate.ts
> +}
O que você acha ?

2022-07-05 00:54 UTC, zDudaHang commented on src/validation/validate.ts
> +  errors = validateGreaterThan(errors, values, "peso", 0);
Acredito que esse `"peso"` e esse `"altura"` poderiam virar constantes

2022-07-05 00:54 UTC, zDudaHang commented on src/validation/validate.ts
> +  if (values[name] && values[name] <= limit) {
Acho que é interessante utilizar os tipos genéricos para garantir que o `errors` seja um `ErrorObject` do `values`, senão pode acabar passando qualquer coisa nessas funções
Dessa forma, você não tem garantia que o `errors` vai ter a prop para aquele `name`

2022-07-05 00:54 UTC, zDudaHang commented on src/components/Formulario.tsx
>    const peso = "peso";
Como você está usando esse `"altura"` e `"peso"` aqui também, talvez seja interessante criando um `model.ts` com essas constantes para usar tanto aqui quanto no validador

2022-07-05 00:54 UTC, zDudaHang commented on src/components/Formulario.tsx
>    const peso = "peso";
Como esses valores nunca vão mudar e não dependem das props do componente, é sempre importante colocar essas variáveis para fora dos componentes também

2022-07-05 14:45 UTC, alisson-fs commented on src/validation/validate.ts
> +}
Nesse caso, acho que eu estaria misturando componente com validação. Para não fazer isso eu teria que criar uma pasta como foi sugerida e dentro dela criar as pastas de componentes e validação. Só que pelo tamanho do projeto isso só deixaria esses arquivos isolados em uma pasta própria. Pensando nesses aspectos, não seria melhor mante-los da forma que estão?

2022-07-06 19:52 UTC, zDudaHang commented on src/validation/validate.ts
> +}
Eu acho que ficaria mais organizado como comentei, mas se você achar melhor assim, pode deixar

2022-07-06 19:52 UTC, zDudaHang commented on src/validation/validate.ts
> +}
Não seria misturar, porque a validação está associada ao componente em si

2022-07-08 12:33 UTC, zDudaHang approved these changes
Top !
Acredito que faltou apenas usar os genéricos na `validateGreaterThan`

2022-07-08 19:13 UTC, merged