Persistindo os cálculos efetuados
alisson-fs/poc-bridge pull request #9
Opened 2022-10-07 20:03 UTC by alisson-fs

2022-10-11 14:58 UTC, zDudaHang requested changes
Top !
Pedi request por causa do teste de integração

2022-10-11 14:58 UTC, zDudaHang commented on backend/src/main/kotlin/br/alisson/poc/model/Imc.java
> +	}
```suggestion

```
Esse override não é mais necessário

2022-10-11 14:58 UTC, zDudaHang commented on backend/src/main/kotlin/br/alisson/poc/model/Imc.java
> +	@Column(name = "co_imc", nullable = false, unique = false)
```suggestion
	@Column(name = "co_imc", nullable = false, unique = true)
```
Um id não seria único ?

2022-10-11 14:58 UTC, zDudaHang commented on backend/src/main/kotlin/br/alisson/poc/model/Imc.java
> +	private Instant dt_calculo;
Acredito que o `nullable` e `unique` já tenham o valor default como false, acho que vale dar uma olhada

2022-10-11 14:58 UTC, zDudaHang commented on backend/src/main/kotlin/br/alisson/poc/service/ImcService.kt
> +        println(tbImc)
Acho que aqui vale usar o [Logger](https://www.baeldung.com/spring-boot-logging) para mostrar a mensagem com o .debug

2022-10-11 14:58 UTC, zDudaHang commented on backend/src/test/kotlin/br/alisson/poc/controller/CalcularImcControllerTest.kt
> +        verify(service).calcularPersistirImc(altura, peso)
Acho que nos casos de erro vale verificar que o `service` não é chamado

2022-10-11 14:58 UTC, zDudaHang commented on backend/src/test/kotlin/br/alisson/poc/controller/CalcularImcControllerIntegrationTest.kt
> +    fun `calcularImc deve retornar um ResponseEntity com o imc correto e HttpStatus OK`() {
Como o imc deve ser salvo depois disso tudo, acredito que faltou verificar se foi salvo no banco
Isso pode ser feito com o [EntityManager](https://javaee.github.io/javaee-spec/javadocs/javax/persistence/EntityManager.html)

2022-10-14 19:05 UTC, alisson-fs commented on backend/src/main/kotlin/br/alisson/poc/model/Imc.java
> +	private Instant dt_calculo;
O `nullable` tem `true` como default.

2022-10-27 15:53 UTC, lucasjoao approved these changes
Boa Alisson! Deixei alguns comentários ali para a gente discutir e deixo a cargo de você avaliar se vai implementar eles ou não.

2022-10-27 15:53 UTC, lucasjoao commented on backend/src/main/kotlin/br/alisson/poc/model/Imc.java
> +	public String toString() {return String.format("IMC(co_imc=%s, nu_altura=%s, nu_peso=%s, nu_imc=%s, dt_calculo=%s", this.id, this.altura, this.peso, this.imc, this.dt_calculo);}
Duda chegou a te passar sobre o lombok? É uma lib beeeeem interessante para o java e bem tranquilo de entender, ela faz automagicamente para os devs vários desses códigos "triviais".

2022-10-27 15:53 UTC, lucasjoao commented on backend/src/main/kotlin/br/alisson/poc/service/ImcService.kt
> +        logger.debug(tbImc)
Será que propósito da tarefa que (se entendi certo) é logar na tela, o mais adequado não seria o nível de info?

2022-10-27 15:53 UTC, lucasjoao commented on backend/pom.xml
> +			<version>2.7.4</version>
Detalhe, mas realmente precisa especificar versão para isso daqui? Ele já não se "vira sozinho" e pega a dependência na versão correta por causa que o teu pom herda do pom do spring-boot?

2022-10-27 15:53 UTC, lucasjoao commented on backend/src/main/kotlin/br/alisson/poc/service/ImcService.kt
> +        return imc.toString()
Só para eu confirmar, ficou acordado com a Duda de retornar o próprio IMC calculado na API, né?

2022-10-27 15:53 UTC, lucasjoao commented on backend/src/test/kotlin/br/alisson/poc/service/ImcServiceTest.kt
> +        nhaarmanVerify(repository).save(any())
Muito complicado tirar esse `any()`?

2022-10-27 15:53 UTC, lucasjoao commented on backend/src/test/kotlin/br/alisson/poc/service/ImcServiceTest.kt
> +        nhaarmanVerify(repository).save(any())
Se tiver dificuldade por causa do `Instant.now()` que tem lá no service, me da um toque na dm

2022-10-27 15:53 UTC, lucasjoao commented on backend/src/test/kotlin/br/alisson/poc/controller/CalcularImcControllerIntegrationTest.kt
> +class CalcularImcControllerIntegrationTest(@Autowired private val controller: CalcularImcController, @Autowired private val entityManager: EntityManager) {
Foi estabelecido com a Duda que o teste de integração seria na camada de controller?

Eu, pessoalmente (e é o que eu vejo sendo feito no pec também) acho que não tem necessidade de teste de integração na camada de controller, mas sim na camada de serviço ou na camada de repository.

No teu caso em específico, recomendaria na camada de serviço.

A razão de eu preferir isso é o seguinte: vamos imaginar que um dia você decida mudar de API Rest para Graphql, então todos os teus testes de integração estarão perdidos e terão que ser refeitos, porque você fez os testes nessa camada. Se os testes tivessem na camada de serviço, não iria ter esse problema.

Assim, acho que o principal aqui é o teu aprendizado (que eu acredito que já está sendo feito entendendo as diferenças entre os testes, a importância deles, como que se faz e agora também tendo essa visão de onde é mais recomendado se testar), então fica a vontade para alterar só se tiver tempo e com vontade.

2022-11-04 18:33 UTC, alisson-fs commented on backend/src/main/kotlin/br/alisson/poc/model/Imc.java
> +	public String toString() {return String.format("IMC(co_imc=%s, nu_altura=%s, nu_peso=%s, nu_imc=%s, dt_calculo=%s", this.id, this.altura, this.peso, this.imc, this.dt_calculo);}
Vou dar uma olhada, valeu pela dica.

2022-11-04 18:34 UTC, alisson-fs commented on backend/src/main/kotlin/br/alisson/poc/service/ImcService.kt
> +        logger.debug(tbImc)
Essa função é auxiliar para que eu conseguisse verificar se os calculos estavam sendo inseridos no banco.

2022-11-04 20:21 UTC, alisson-fs commented on backend/src/main/kotlin/br/alisson/poc/service/ImcService.kt
> +        return imc.toString()
A função deve retornar o IMC calculado, retornar ele como string foi uma escolha de desenvolvimento.

2022-11-07 12:27 UTC, zDudaHang commented on backend/src/main/kotlin/br/alisson/poc/model/Imc.java
> +	public String toString() {return String.format("IMC(co_imc=%s, nu_altura=%s, nu_peso=%s, nu_imc=%s, dt_calculo=%s", this.id, this.altura, this.peso, this.imc, this.dt_calculo);}
Nossa, verdade né :eyes: 
Ela é uma mão na roda mesmo

2022-11-07 12:28 UTC, zDudaHang commented on backend/src/test/kotlin/br/alisson/poc/controller/CalcularImcControllerIntegrationTest.kt
> +class CalcularImcControllerIntegrationTest(@Autowired private val controller: CalcularImcController, @Autowired private val entityManager: EntityManager) {
Boa, faz bem mais sentido mesmo !

2022-11-07 17:35 UTC, lucasjoao approved these changes

2022-11-07 17:39 UTC, lucasjoao approved these changes

2022-11-07 17:44 UTC, alisson-fs commented on backend/pom.xml
> +			<version>2.7.4</version>
É isso mesmo, fiz o teste e funcionou.

2022-11-07 17:46 UTC, lucasjoao approved these changes

2022-11-07 18:20 UTC, zDudaHang approved these changes
Top !
Deixei só duas sugestões :relaxed:

2022-11-07 18:20 UTC, zDudaHang commented on backend/src/main/kotlin/br/alisson/poc/model/Imc.java
> +	protected Imc() {}
Esse construtor poderia ser substituído pela anotação `@NoArgsConstructor` do Lombok

2022-11-07 18:20 UTC, zDudaHang commented on backend/src/test/kotlin/br/alisson/poc/service/ImcServiceIntegrationTest.kt
> +    fun `calcularPersistirImc deve retornar o imc correto`() {
```suggestion
    fun `calcularPersistirImc deve retornar o imc correto e persistir o resultado na tabela`() {
```

2022-11-07 19:38 UTC, merged